### ISSUE TITLE
Catching an invalid Steam ID exception.

### ISSUE THREAD

**Issue by RonMelkhior** [xPaw/SteamID.php#10]
Hi!

``` php
try { // Attempt initializing a SteamID instance with the input.
    $providedID = new SteamID($id);
} catch(InvalidArgumentException $e) { // Invalid ID, can be a custom URL thing. Or a URL.
    echo 'Invalid ID....';
}
```

Using this code, On PHP 7.0.4, it doesn't actually catch the exception and just throws out a fatal error and exits the page. Am I doing something wrong?

Cheers.

**Comment by RonMelkhior** [comment]
Solved this myself, for anyone who wants to know the fix, add \ before the InvalidArgumentException.

``` php
try { // Attempt initializing a SteamID instance with the input.
    $providedID = new SteamID($id);
} catch(\InvalidArgumentException $e) { // Invalid ID, can be a custom URL thing. Or a URL.
    echo 'Invalid ID....';
}
```

**Comment by borzaka** [comment]
I had to use
`throw new \InvalidArgumentException`
instead of
`throw new InvalidArgumentException`
in the _SteamID.php_ at every occurrence.

Maybe I namespacing something wrong?
I use `require_once("../application/Libs/SteamID.php");`
