### ISSUE TITLE
Request: Add support for vanity urls without protocol

### ISSUE THREAD

**Issue by iNilo** [xPaw/SteamID.php#12]
It would be nice to have buildin support for urls without protocol (http/https)
So we can input `steamcommunity.com/id/xpaw`
And not `http://steamcommunity.com/id/xpaw`

**Comment by xPaw** [comment]
Changing regex `^https?:\/\/` to `^(?:https?:\/\/)?` should make it work, needs tests though.

**Comment by iNilo** [comment]
afaik steam API requires the protocol, so might need to add it if its missing

**Comment by xPaw** [comment]
The API only takes the name (e.g `xpaw`), not full url, so that doesn't matter.
