### ISSUE TITLE
Error in steamid Processing  STEAM_#

### ISSUE THREAD

**Issue by FennixCoding** [xPaw/SteamID.php#14]
I am using your script for a donation script im building, the problem is simple, when retreiving a normal steamid " STEAM_1:0:7828#####" for example it should be "STEAM_0:0:7828#####"

it keeps saying its steam_1 not steam_0.

This is a example:
https://steamid.io/lookup/76561198116838208

if you notice its STEAM_0, but if you enter STEAM_1 itll show it as STEAM_0.

**Comment by xPaw** [comment]
That's not a bug in the library. Games before orange box used to incorrectly display as STEAM_0
