### ISSUE TITLE
GMP errors despite installing the module

### ISSUE THREAD

**Issue by bayrock** [xPaw/SteamID.php#16]
I'm running PHP version 7.1.32-1+ubuntu18.04.1

I've tried numerous times to install the GMP module for this PHP version. I edit the php.ini to ensure the gmp extension is included, but no matter what I'm always receiving the following error:

`An exception occurred: Call to undefined function gmp_init() in /var/www/example.org/public_html/library/PageBansCP/SteamID.php on line 126`

Any suggestions to get this module working?

**Comment by xPaw** [comment]
Not a problem with this library. Try asking on stackoverflow.

**Comment by bayrock** [comment]
Thanks for the response, I'll try StackOverflow. 

For future reference the GMP module was not being installed due to a (misconfigured?) GRUB installation. I proceeded to follow this StackOverflow answer to get GRUB installed properly:
https://stackoverflow.com/a/53284186

After that I was able to successfully install the GMP module for my version of PHP, and I can use the SteamID library in peace.
