### ISSUE TITLE
Steam Vanity Lookup Failing to perform API request

### ISSUE THREAD

**Issue by jortuck** [xPaw/SteamID.php#17]
Hello. I'm having a bit of an odd issue where the Vanity URL lookup just stopped working. I'm not quite sure what's causing it because it's been working for the past few months and just stopped working now.  I have a feeling Steam may have changed something in their API because it stopped working across multiple projects of mine. I also know that I haven't reached my API limit for the day because I can still access the API manually through my browser.

I am using the same code you provided in the VanityURL's php file. I happend to notice that SteamID's, SteamID64's, and SteamID3's still work, however when looking up Vanity URL's (https://steamcommunity.com/id/driedsponge, driedsponge) the API request failed.

Any help would be appreciated. Thank you!

**Comment by xPaw** [comment]
"VanityURL" file is only an example on how to implement the provider, that's on you to do it correctly.

The vanity API still works just fine (you can confirm that on steamdb.info/calculator).

> I happend to notice that SteamID's, SteamID64's, and SteamID3's still work

They still work because only resolving vanity urls requires the web api.

**Comment by jortuck** [comment]
Alright thank you.
