### ISSUE TITLE
Add namespace

### ISSUE THREAD

**Issue by DeCodeerHeer** [xPaw/SteamID.php#18]
Autoloading the SteamID.php trough composer without namespace throws the following error in a laravel setup.

![image](https://user-images.githubusercontent.com/22918553/79670080-aaf35880-81c0-11ea-8062-1f3b8ad20dce.png)

**Comment by xPaw** [comment]
Well, are you trying to call `Get`? Show code.

**Comment by xPaw** [comment]
This doesn't look like a namespace problem.

**Comment by DeCodeerHeer** [comment]
Adding a namespace fixed the issue.

**Comment by xPaw** [comment]
Show your code, I don't see how the exception on your screenshot is related to namespacing.

**Comment by DeCodeerHeer** [comment]
There is nothing more to show that the magic of laravel calling your class. It might be calling a string referring 'steamid' and calling your class because without namespace it's inteprented as a function.

**Comment by xPaw** [comment]
Sounds like laravel is trying to do too much magic. I use this class with an autoloader and it works just fine.

**Comment by Snakzi** [comment]
> 
> 
> Adding a namespace fixed the issue.

whats the namespace tho?
