### ISSUE TITLE
Cannot convert 32-bit IDs to 64-bit

### ISSUE THREAD

**Issue by Bilge** [xPaw/SteamID.php#20]
Although `SteamID` can be constructed with a 64-bit ID, it does not have a function to consistently emit 64-bit IDs, despite what `ConvertToUInt64()` might imply. That is, `ConvertToUInt64()` is just a round-trip function and doesn't actually convert anything:

```php
(new SteamID('1'))->ConvertToUInt64() // "1"
````

Contrast this with `GetAccountID()`, which actually does consistently output the 32-bit form of the account ID. There should be a 64-bit analogue of this method.

**Comment by xPaw** [comment]
This behavior is correct, you have to provide the other bits yourself.

```php
function AccountIDToSteamID( int $AccountID ) : string
{
	$SteamID = new SteamID();
	$SteamID->SetAccountUniverse( SteamID::UniversePublic );
	$SteamID->SetAccountInstance( SteamID::DesktopInstance );
	$SteamID->SetAccountType( SteamID::TypeIndividual );
	$SteamID->SetAccountID( $AccountID );

	return $SteamID->ConvertToUInt64();
}
```

Alternatively pass it to constructor as a string: `[U:1:12345]` where `12345` is the account id.
