### ISSUE TITLE
Wrong SteamID with RenderSteam2() function

### ISSUE THREAD

**Issue by Alexell** [xPaw/SteamID.php#23]
Hello. I have been seeing this problem for a long time, I just rarely use the conversion from Steam64 to Steam2, so I did not report it before.
Problem: **Wrong universe**.

**Code example:**
```
<?php
require __DIR__ . '/inc/SteamID.php';

$sid64 = 76561198210303223; // really sid: STEAM_0:1:125018747
$s = new SteamID($sid64);
echo $s->RenderSteam2(); // STEAM_1:1:125018747

$sid64 = 76561197990364979; // correct sid: STEAM_0:1:15049625
$s = new SteamID($sid64);
echo $s->RenderSteam2(); // STEAM_1:1:15049625

$sid64 = 76561198166638169; // correct sid: STEAM_0:1:103186220
$s = new SteamID($sid64);
echo $s->RenderSteam2(); // STEAM_1:1:103186220
```

This problem is observed on the release version **2.0.0**, also on the **current** github version.
I checked version 2.0.0 on php **7.4.3** and the current version on php **8.1** - in both cases the problem is present.

**Comment by xPaw** [comment]
STEAM_0 is not correct because the public universe is 1.

0 used to be displayed with old games, but that's about it.

See: https://github.com/xPaw/SteamID.php/blob/6737441aa7f1358d047974112ea95c89e98f1c1c/SteamID.php#L138-L144

Better yet, just avoid using Steam2 if you can.

**Comment by Alexell** [comment]
We play Garry's Mod. On servers, all players' SteamID starts with STEAM_0
I just checked the latest new players in the database - they have the same. Nothing has changed. How can we be?

**Comment by xPaw** [comment]
You should be able to `SetAccountUniverse( 0 );` before rendering it.

**Comment by Alexell** [comment]
Checked. Now it works fine. Thank you!
