### ISSUE TITLE
STEAM_0-prefixed IDs emitted as STEAM_1-prefixed

### ISSUE THREAD

**Issue by Bilge** [xPaw/SteamID.php#26]
`STEAM_0:1:124` (and a bunch of other `STEAM_0`-prefixed IDs) are showing up as `STEAM_1` when output by `RenderSteam2` method. [Other sites](https://steamid.uk/profile/76561197960265977) also corroborate that this should be `STEAM_0`-prefixed.

```php
echo (new \SteamID('STEAM_0:1:124'))->RenderSteam2(); // STEAM_1:1:124
```

**Comment by xPaw** [comment]
https://github.com/xPaw/SteamID.php/blob/c547fb93a3b478023d7d6c89e6e82b5115235a59/SteamID.php#L140-L144

This is intentional. And I won't change it because it's really just time to move from these old ids.

**Comment by KO-9** [comment]
This is intentional. And I won't change it because it's really just time to move from these old ids.

So you're saying anyone with an old account should just ditch it for the sake of devs?

**Comment by xPaw** [comment]
Old accounts have nothing to do with it (and not how it works). Your account has an accountid on public universe, it's broken down here: https://github.com/xPaw/SteamID.php?tab=readme-ov-file#brief-overview

**Comment by KO-9** [comment]
The code you linked above handles constructing a new instance using Steam32. The issue is when you construct using something else and then use $s->GetAccountUniverse() - you're given the incorrect universe of 1 instead of 0 - this is an issue for $s->RenderSteam2()
