### ISSUE TITLE
Parsing of account ID goes weird

### ISSUE THREAD

**Issue by iNilo** [xPaw/SteamID.php#9]
```
    $steam = new SteamID();
    $steam->SetAccountID(48251305);
    var_dump($steam->ConvertToUInt64());
        //reparse
    $steam = new SteamID($steamshit->RenderSteam2());
    var_dump($steam->ConvertToUInt64());
```

> string(8) "48251305"
> string(17) "76561198008517033"

**Comment by xPaw** [comment]
You never set instance, universe or type. Of course the conversion isn't going to be 1:1 with half the data missing.

https://github.com/xPaw/SteamID.php#steamid-normalization
